#!/usr/bin/env python3
''' Command Line Interface - Sync Folders '''

import os
import click

def validate_path(_, param, value):
    ''' Click argument validator - ensure arguments are directories '''
    if (param.name == 'destination') and folder_not_exists(value):
        click.echo('Destination folder not found. Creating: %s' % value)
        os.makedirs(value)
    if not os.path.isdir(value):
        msg = ''
        if os.path.isfile(value):
            msg = ' - %s is a file' % (value)
        raise click.BadParameter('%s needs to be a valid directory %s' % (param.name, msg))
    return value

def folder_not_exists(path):
    ''' Check if given path is not an existing file or folder '''
    return (not os.path.isfile(path)) and (not os.path.exists(path))

@click.command()
@click.argument('source', type=click.Path(exists=True), callback=validate_path, nargs=1)
@click.argument('destination', type=click.Path(), callback=validate_path, nargs=1)
def sync_folders(source, destination):
    """
    Sync the contents of source folder with destination.
    Essentially - backup the source to the destination.
    """
    click.echo('Syncing %s to %s' % (source, destination))

if __name__ == '__main__':
    sync_folders() # pylint: disable=no-value-for-parameter
