#!/usr/bin/env python3

import click
import os

def validate_path(ctx, param, value):
    if (param.name == 'destination') and (not os.path.isfile(value)) and (not os.path.exists(value)):
        click.echo('Destination folder not found. Creating: %s' % value)
        os.makedirs(value)
        return
    if not os.path.isdir(value):
        msg = ''
        if os.path.isfile(value):
            msg = ' - %s is a file' % (value)
        raise click.BadParameter('%s needs to be a valid directory %s' % (param.name, msg))

@click.command()
@click.argument('source', type=click.Path(), callback=validate_path)
@click.argument('destination', type=click.Path(), callback=validate_path)

def sync_folders(source, destination):
    """
    Sync the contents of source folder with destination.
    Essentially - backup the source to the destination.
    """
    click.echo('Syncing %s to %s' % (source, destination))
    pass

if __name__ == '__main__':
    sync_folders()
